name: tbChaSIn
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  # Pipeline
  - snakemake-minimal=7.32.4
  - bwa=0.7.17
  - picard=3.1.1 # can use picard-slim when R is not required
  - fgbio-minimal=2.2.1
  - fastqc=0.12.1
  - multiqc=1.17
  - samtools=1.19.2
  - fgsv=0.1.1
  # pytomebio
  - defopt=6.4.0
  - pysam=0.22.0
  - biopython=1.83
  # Testing
  - pytest=8.0.0
  - ruff=0.2.1
  - mypy=1.8.0
  - shellcheck=0.9.0
  - types-pyyaml=6.0.12.12
  - pip=24.0
  - fgpyo=0.1.2
  - fastp=0.23.4
