name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-file: environment.yml
        condarc: |
          channels:
            - bioconda
            - conda-forge
        cache-environment: true
        post-cleanup: 'all'
    - name: Run pre-commit testing
      shell: micromamba-shell {0}
      run: |
        bash ci/precommit.sh
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: tomebio/cryptic-seq:1.0
